apiVersion: v1
kind: Service
metadata:
  name: homework-service
  namespace: homework
  labels:
    app: homework
spec:
  selector:
    app: homework
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000